# .air.toml
# Config file for Air - https://github.com/cosmtrek/air

# Working directory
# . or absolute path, please note that the directories following must be under root
root = "."
tmp_dir = "tmp" # Directory for temporary files like the compiled binary

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./tmp/main cmd/server/main.go"
# Binary file yields from `cmd`.
bin = "tmp/main"
# This command will be executed when `bin` is up.
full_bin = "./tmp/main" # You can add environment variables here if needed, e.g., "APP_ENV=dev ./tmp/main"

# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html", "css"]
# Ignore these filename extensions or directories.
exclude_dir = ["assets", "tmp", "vendor", "node_modules"]
# Watch files in these directories.
include_dir = []
# Exclude files from watching.
exclude_file = []
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false
# Delay after sending Interrupt signal
kill_delay = 500 # ms

[log]
# Show log time
time = true

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true 