// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type PaidRoute struct {
	ID           int64
	ShortCode    string
	TargetUrl    string
	Method       string
	Price        int32
	IsTest       bool
	UserID       int32
	IsEnabled    bool
	AttemptCount int32
	PaymentCount int32
	AccessCount  int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    pgtype.Timestamptz
}

type Purchase struct {
	ID             int64
	ShortCode      string
	TargetUrl      string
	Method         string
	Price          int32
	IsTest         bool
	PaymentPayload []byte
	SettleResponse []byte
	PaidRouteID    int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	ID        int64
	Email     string
	Name      string
	GoogleID  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
